version: "3"

services:
  web:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./wwwroot:/usr/share/nginx/html
    depends_on:
      - default
    networks:
      - site
  default:
    restart: always
    build: ./fpm
    volumes:
      - ./wwwroot/default:/var/www/html
    networks:
      - site

networks:
  site:
    driver: bridge

