version: "3"

services:
  web:
    container_name: web
    image: flxxyz/nginx:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rewrite.d:/etc/nginx/rewrite.d
      - ./log:/var/log/nginx
      - ./wwwroot:/usr/share/nginx/html
    depends_on:
      - default
      - default-cli
    networks:
      - site
  default:
    container_name: default
    restart: always
    image: flxxyz/php:7.3-fpm
    volumes:
      - ./wwwroot/default/conf/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./wwwroot/default/conf/php.ini:/usr/local/etc/php/php.ini
      - ./wwwroot/default:/var/www/html
    networks:
      - site
  default-cli:
    container_name: default-cli
    restart: always
    image: flxxyz/php:7.3-cli
    volumes:
      - ./wwwroot/default-cli/www:/usr/src/myapp
    command: php /usr/src/myapp/index.php
    networks:
      - site

networks:
  site:
    driver: bridge

