version: "3.7"

services:
  web:
    container_name: web
    image: flxxyz/nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rewrite.d:/etc/nginx/rewrite.d
      - ./log:/var/log/nginx
      - ./wwwroot:/usr/share/nginx/html
    networks:
      - site
  default:
    container_name: default
    restart: always
    image: flxxyz/php:7.3-fpm
    volumes:
      - ./wwwroot/default/conf/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./wwwroot/default/conf/php.ini:/usr/local/etc/php/php.ini
      - ./wwwroot/default:/var/www/html
    networks:
      - site
  default-cli:
    container_name: default-cli
    restart: always
    image: flxxyz/php:7.3-cli
    volumes:
      - ./wwwroot/default-cli/www:/usr/src/myapp
    depends_on:
      - composer
    command: php /usr/src/myapp/index.php
    networks:
      - site
  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./wwwroot/default-cli/www:/app
    command: composer install -vvvv
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
  laravels:
    container_name: laravels
    restart: always
    image: flxxyz/php:7.3-cli
    ports:
      - "8111:9502/tcp"
      - "8222:9503/udp"
    volumes:
      - ./wwwroot/laravels/conf/php.ini:/usr/local/etc/php/php.ini
      - ./wwwroot/laravels/www:/usr/src/myapp
    depends_on:
      - laravels-composer
    command: php bin/laravels start
  laravels-composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./wwwroot/laravels/www:/app
    command: composer install -vvvv
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  site:
    driver: bridge

