version: '3'

services:
  web:
    image: flxxyz/alpine-nginx-php7:latest
    ports:
      - 80:80
      - 443:443
      - 7070:7070
    volumes:
      - ./data/conf/nginx:/data/conf/nginx
      - ./data/site:/data/site
      - ./data/log:/data/log
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
