version: '3'

services:
  web:
    image: flxxyz/alpine-nginx-php7:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/conf/nginx:/etc/nginx
      - ./data/conf/php:/etc/php7
      - ./data/site:/data/site
      - ./data/log:/data/log
      - ./data/log:/var/lib/nginx/logs
      - ./data/log:/var/log/nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
